spring:
  datasource:
    url: jdbc:mysql://localhost/loja?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always # utiização do data.sql só funcionou com essa configuração
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDBDialect
