server:
  port: 8888

# Configuração abaixo para acessar sistema de arquivos
#spring:
#  profiles:
#    active:
#    - native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations:
#          - C:/dsn/back/microservices

# Configuração abaixo para acessar repositório no git
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/igorcastro-dsn/spring-cloud
          search-paths:
          - /configs/fornecedor